---
title: "20240917_Building_Blocks_Lecture_2"
author: "Kaleb J. Frierson"
date: "2024-09-17"
output: html_document
---

# Notes

Today is data wrangling lecture. 

Tibbles are data frames, slightly different. Much better. Intended to solve problems that have emerged with data frames. Faster, more memory efficient, force you to do best practices. By default, anything that you import using tidyverse code will be a tibble. 

So what is a tibble? 

80/20 rule: 80% of import cases only take 20% of your time. 20% however will take like 80% of your time. 

Need to learn readr package, haven, readxl 

Readr is great for csv files and is common way to import. Readxl is great for excel spreadsheets. Haven is great for bringing data from other packages. 

Should be thoughtful about your data. Know what it should look like. See things that might be wrong, and why are they wrong? Something should be a number but it isn't, why is that the case? 

When you are doing data wrangling, you want the most raw data. It helps you get to know the data and makes the entire process reproducible. 

# Data Import


